### ISSUE TITLE
Multiple BB Users

### ISSUE THREAD

**Issue by AdherenceDigital** [highrisedigital/wpbroadbean#19]
Hi Mark

Thanks for looking at this. I am new to Broadbean (having been asked by a potential client on becoming BB compliant) so I apologise that my knowledge of how BB works is limited. :)

What would be great would be the ability to add multiple feeds into the plugin that represent different clients. So for example:

- Say I have 5 clients all using BB. Each of them are able to create a feed specifically for my site which is an external 3rd party site (like www.jobsinkent.com)
- Within the plugin settings page, I would be able to set up more than one feed, one for each client.
- An additional label field would be useful so I am easily able to identify which feed pertains to which client.
- Each feed then populates WP in the normal way 
- Should a feed not work for some reason, a notification is sent via email to the admin profile to alert them that the feed is not working.

As mentioned I am not entirely sure how BB works so forgive me for the next suggestion.
- Cron job functionality so the feeds could update overnight (this might already be the case).

I hope this has enough detail? Thanks for your time.

Warm regards
Peter

**Comment by wpmark** [comment]
So that I have understood this correctly - you want a client (who logs into Broadbean to post jobs) to be able, as well as posting to other job boards, to be able to send a job to your site. So you would like your site to appear in Broadbean as a job board?

**Comment by AdherenceDigital** [comment]
Yes. The part about appearing in Broadbean as a job board I am not sure about (is that mandatory or a result of using BB?). 

The plugin looks like it can only accept one feed (Client A) so if I have Client B who also wishes to post to my site they are unable to at present.

Thanks
Peter

**Comment by wpmark** [comment]
> The plugin looks like it can only accept one feed

I think this is where you are getting confused. The plugin accepts data sent to it, authenticated with a username and password in an XML format. There is no limit on where the data comes from and therefore you could have multiple people send data to it.

**Comment by AdherenceDigital** [comment]
Ah very interesting. So if I set up a username and feed, and hand that out to all clients, they then set up in BB the same credentials, that should be it?

I was given the impression the feeds had to be unique per BB user and could not be duplicated, therefore multiple feed functionality was required. Am I able to donate to your plugin?

**Comment by wpmark** [comment]
It sounds to me like you want your site setup with Broadbean as a job board. Then your clients, will get access to choose your job board when they post jobs.

I have integrated this solution before for clients. In terms of donating your very kind, see the link in the plugin readme file:

https://github.com/wpmark/wpbroadbean/blob/master/readme.txt#L3

**Comment by AdherenceDigital** [comment]
I see. I approached this completely back to front :)

Thanks for your help Mark and I will see to a donation.
Warm regards
Peter
