### ISSUE TITLE
Allow Output to be Turned off with a Setting

### ISSUE THREAD

**Issue by wpmark** [highrisedigital/wpbroadbean#24]
At the moment on the single job page the plugin outputs the job fields and the jobs taxonomy terms by filtering the post content. The plan here is to provide an option in the settings screen to turn off this output.

**Comment by wpmark** [comment]
This setting would have to be on by default.

**Comment by hamblyfreeman** [comment]
This would be incredibly useful...

**Comment by MattPurland** [comment]
+1

I find it rather annoying that wherever I've used the_content filter throughout my theme I now get a 'Error: No job reference detected!' message

**Comment by wpmark** [comment]
@MattPurland can you give an example of when you are using `the_content` filter please?

**Comment by MattPurland** [comment]
@wpmark I'll admit I wasn't very clear, my apologies.

I use CMB2 for custom meta fields, including WYSIWYG fields, which need to be filtered through the_content to be correctly formatted

**Comment by wpmark** [comment]
Fixed with the release of version 2.2.3

https://github.com/highrisedigital/wpbroadbean/releases/tag/v2.2.3
