### ISSUE TITLE
Make auto-deletion of CVs toggleable

### ISSUE THREAD

**Issue by sijones-uk** [highrisedigital/wpbroadbean#33]
[This commit](https://github.com/highrisedigital/wpbroadbean/commit/09e04a0f41b0dcf5066775157e786dc015affd39) deletes CVs after they've been sent. Could that be made toggleable? Our client wants to keep the CVs on the system (I think in case the attachment gets stripped by their email system).

**Comment by wpmark** [comment]
@sijones-uk this is actually toggleable with code by using the filter in the file. Take a look here:

https://github.com/highrisedigital/wpbroadbean/blob/master/functions/application-form.php#L379-L385

**Comment by sijones-uk** [comment]
Thanks Mark - I didn't realise you'd added that in a subsequent commit.
