### ISSUE TITLE
PHP 7 Support

### ISSUE THREAD

**Issue by bencorke** [highrisedigital/wpbroadbean#34]
After enabling PHP 7, taxonomies are no longer being added to job posts. 

- Notice: Array to string conversion in inbox.php [line 83](https://github.com/highrisedigital/wpbroadbean/blob/91b075cfa1fa513ab839b66313880437778b183b/inbox.php#L83)
- Notice: Array to string conversion in inbox.php line 148

```
// inbox.php L83 

if( $wpbb_xml_params->$taxonomy[ 'bb_field' ] == '' ) {
			continue;
		}
```

I enabled PHP 7 in cPanel by adding  `AddHandler application/x-httpd-php70 .php` to .htaccess

[http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling](http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling)

I think I noticed a few support requests on the WordPress forums and elsewhere complaining of Taxonomies not being added to posts. Might be why.

The fix for now was to return PHP5 however, PHP7 seems more performant, so would be nice to have support.

Thanks,
Ben

**Comment by wpmark** [comment]
Hi Ben, I have actually been working through this issue with another client and we have a fix for this which I will push out asap. It is all to do with variable variables and PHP7. Thanks for bringing this up.

**Comment by wpmark** [comment]
Hi @bencorke I have now pushed a fix for this to develop branch:

https://github.com/highrisedigital/wpbroadbean/tree/develop

Could you test for me please on PHP 7?

**Comment by bencorke** [comment]
Hi @wpmark 

> Could you test for me please on PHP 7?

Quick test mind, but seems to be working fine. 

Cheers,
Ben

**Comment by wpmark** [comment]
This has been merged into a release now and should be available through WordPress updates. Thanks for your help with this issue.
