### ISSUE TITLE
Error: Invalid XML or no XML supplied.

### ISSUE THREAD

**Issue by MiriShehu** [highrisedigital/wpbroadbean#38]
www.domain.com/?wpjmbb=broadbean (invalid xml or no xml supplied)

Sorry for not giving to much explanations but I'm new to this plugin. I can't figure out what is the issue

**Comment by wpmark** [comment]
@MiriShehu for support please use the WordPress.org support forum for the plugin.

https://wordpress.org/support/plugin/wpbroadbean/
