### ISSUE TITLE
Application status stuck in draft

### ISSUE THREAD

**Issue by hamblyfreeman** [highrisedigital/wpbroadbean#40]
For some reason, over the last few months, all applications have started to arrive with a status of draft rather than published, which is causing some issues elsewhere.

Why would this be and how can I change this?

Thanks in advance.

**Comment by wpmark** [comment]
The latest release made applications no longer have a published status, to make sure they were not going to show on the front-end of a site:

https://github.com/highrisedigital/wpbroadbean/releases/tag/v2.2.2

You can always override this using the `wpbb_insert_application_args` filter which is used here:

https://github.com/highrisedigital/wpbroadbean/blob/master/functions/application-form.php#L264-L274

**Comment by hamblyfreeman** [comment]
Thanks for the swift reply, Mark.

Is this correct?

`//	FIX APPLICATIONS STATUS

function wpbb_make_applications_published( $args ) {

	$args[ 'wpbb_insert_application_args' ] = array(
		'post_status'	=> 'pubished'
	);

	return $args;

}

add_filter( 'wpbb_insert_application_args', 'wpbb_make_applications_published' );`

**Comment by wpmark** [comment]
Not quite. This should do the trick though.

```php
/**
 * Edits the args passed to wp_insert_post when an application is created.
 *
 * @param  array $args The current array of insert post args.
 * @return array       The modified array of insert post args.
 */
function myprefix_edit_insert_application_args( $args ) {
	
	// change the status of the newly created applications to publsh.
	$args['post_status'] = 'publish';

	// return the edited args.
	return $args;

}

add_filter( 'wpbb_insert_application_args', 'myprefix_edit_insert_application_args' );
```
