### ISSUE TITLE
How to setup custom fields in feed?

### ISSUE THREAD

**Issue by HeadStudios** [highrisedigital/wpbroadbean#48]
Hi,

I have a custom meta field ('agent') that I would like to update for the job that can be included in the XML file. Can you give an overview of how this can be done? Also once it's executing I need to add another meta field on the backend - but if the first question is answered that's the main one. Like if Broadbean sends the XML with 'agent' for example will that be automatically added as a meta?

Thanks

**Comment by bencorke** [comment]
If 'agent' is the recruiter, you might want to ask BB to allow mapping of WordPress User ID to BB users in your BB integration and send this user it in the `agent` xml field:

1. Set up user in WP
2. Add WP user ID's in BroadBean admin for each user in your integration
3. Add 
`'post_author'  => wp_strip_all_tags( (string) $wpbb_xml_params->agent ),` 
in `$wpbb_insert_job_post_args` located in your custom inbox.php

Drawback is remembering to set up the user in WP and BB. 

OR

If you simply just want to add an `Agent` field as a custom field with no WP author association, add this to functions.php

n.b. not tested in 3x, only 2x

```
//   ADD EXTRA CUSTOM FIELD AGENT
add_filter( 'wpbb_job_fields', 'wpbb_add_extra_fields',10 );

function wpbb_add_extra_fields( $fields ) {
    
   /* add  new field to the array of existing fields */
    $fields[ 'agent' ] = array(

        // label shown in the WordPres admin
        'name'      => 'Agent',

        // this is the meta key - best prefixed with _wpbb_ to be consistent
        'id'        => '_wpbb_agent',

        // this is the XML field for this job field which broadbean will send the value in
        'bb_field'  => 'agent',

        // description to show in the admin near the label and input
        'desc'      => 'Agent responsible',

        // the type of input this show be in the admin e.g. text, select, textarea
        'type'      => 'text',

        // whether you can edit the field in the post edit screen - true means you can't
        'readonly'  => false,

        // layout columns on a 12 column grid
        'cols'      => 6,

        // show or hide the field from being outputted on the job permalink template
        'show_on_frontend' => true
    );
  
  return $fields;
}
```

Cheers,
Ben

**Comment by wpmark** [comment]
Thanks for helping out here Ben!

The code Ben posted above should work, but only in 2. branch, not with version 3. branch. In addition, for the first part of the code, instead of having your own copy of the `inbox.php` file on your theme, you could add to the `args` passed to `wp_insert_post()` using the `wpbb_insert_job_post_args` filter.

**Comment by HeadStudios** [comment]
Thank you for your extensive input - for the record this is an ACF field - so there are two meta fields (the names exactly) are 
'agent' - contains ID of the agent (so it's not based on user as per your first example)
'_agent' - this contains a long field like 'field_ads332as' but it's the same for each custom job type - I tried to add it but it's not working.

By the way I thought the program automatically added a custom meta field if a new field was added through XML - but it seems this is not the case? In other words for every additional field type that I would like imported outside of what is setup I have to setup that code?

Any additional input you could give would be great.

Also some sample PHP to text an XML send to the endpoint as right now it's being done by Broadbean would be helpful also.

Thanks!

**Comment by HeadStudios** [comment]
It's ok I've setup XML test - just trying to get this custom field working. Will test your solution now.

**Comment by HeadStudios** [comment]
Hi,
I've just tested it and a new agent field is appearing but I want it to work with ACF - as you can see there is now a double up
https://cl.ly/006a36491e9b

Thanks
P.S. So all i really want is when <agent>322</agent> is sent through the post meta is updated with
'agent' => 322
'_agent' => 'field_ebe3233' (as an example - this value stays the same for every job custom post meta type)

Thanks

**Comment by HeadStudios** [comment]
It's ok I figured it out - thanks.

**Comment by wpmark** [comment]
Be great if you could post the answer here for others please 🤞
