### ISSUE TITLE
Error in filter wpbb_post_title_text

### ISSUE THREAD

**Issue by bencorke** [highrisedigital/wpbroadbean#49]
release: 3.0.2
PHP: 7.1
debug/errors: on

/inc/filters.php:140  ` return apply_filters( 'wpbb_post_title_text', $title, $wpbb_screen );`

`$wpbb_screen` throws an undefined error

should probably be:
/inc/filters.php:140   `return apply_filters( 'wpbb_post_title_text', $title, $screen );`

Cheers,
Ben

**Comment by wpmark** [comment]
Thanks for reporting this Ben. I am in the middle of a release for version 3.03 with some other minor fixes and this will be done in that release.

**Comment by wpmark** [comment]
Fixed in version 3.0.3
