### ISSUE TITLE
Is wpbb_job_salary_currency_symbol function missing in latest version?

### ISSUE THREAD

**Issue by boostonline** [highrisedigital/wpbroadbean#51]
[08-Aug-2019 12:28:12 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wpbb_job_salary_currency_symbol() in /home/pearsonwhiffin/public_html/wp-content/themes/pearson-whiffin-2017/single-wpbb_job.php:51
Stack trace:
#0 /public_html/wp-includes/template-loader.php(78): include()
#1 /public_html/wp-blog-header.php(19): require_once('/home/pearsonwh...')
#2 /public_html/index.php(17): require('/home/pearsonwh...')
#3 {main}
  thrown in /public_html/wp-content/themes/pearson-whiffin-2017/single-wpbb_job.php on line 51

**Comment by wpmark** [comment]
Yes this function is no longer included. It is worth remembering that the plugin update to version 3.0 did have breaking changes and updating from 2 to 3 needs testing and work.
